server:
  port: 8080

#logging:
#  file: springboot.log

spring:
  messages:
    basename: i18n.index
  thymeleaf:
      cache: false

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
#  url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.11.162)(PORT = 1521))(CONNECT_DATA = (SERVER = DEDICATED)(SERVICE_NAME = dbtest)))
    url: jdbc:oracle:thin:@192.168.11.162:1521:dbtest
    username: li
    password: li

mybatis:
#    mapper-locations: classpath:com/cwn/springboot/mapper/*.xml
    mapper-locations: classpath:mapper/*.xml

resources: # 指定静态资源的路径
      static-locations: classpath:/static/,classpath:/templates/
      cache-period: 0

file: #访问绝对路径下的静态资源
  staticAccessPath: /images/**
  uploadFolder: d://uploadFiles/
  deluploadFolder: d:/uploadFiles/

web:
  uploadpath: /images/